---
- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.4.0  # put latest release tag from https://github.com/ansible/ansible-lint/releases/
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

...
