---
# install image builder packages and enable osbuild-composer service
rhel_image_builder_install: true
rhel_image_builder_packages:
  - osbuild-composer
  - composer-cli
  - bash-completion

# install cockpit-related packages and enable cockpit service
rhel_image_builder_install_cockpit: false
rhel_image_builder_cockpit_packages:
  - cockpit
  - cockpit-composer

# list of additional packages to include in the image, for example
#   - name: tmux
#   - name: aide
#     version: '*'
rhel_image_builder_blueprint_packages: []

# image builder customizations
rhel_image_builder_blueprint_hostname: ''
rhel_image_builder_blueprint_users: []
rhel_image_builder_blueprint_groups: []
rhel_image_builder_blueprint_sshkeys: []

# documentation is confusing on the difference between
# customizations.kernel.name and customizations.kernel.name.name,
# and a blueprint push complains if both are set, so only support
# the former for now
rhel_image_builder_blueprint_kernel: []
#  name: ''
#  append: ''

rhel_image_builder_blueprint_timezone: []
#  timezone: ''
#  ntpservers: []

rhel_image_builder_blueprint_locale: []
#  languages: []
#  keyboard: ''

rhel_image_builder_blueprint_firewall: []
#  ports: []
#  services:
#    enabled: []
#    disabled: []

rhel_image_builder_blueprint_services: {}
#  enabled: []
#  disabled: []

rhel_image_builder_blueprint_filesystems: []

# debugging prevents artifact cleanup so they can be reviewed as needed
rhel_image_builder_debug: false

# image formats to build
# - type is one of `composer-cli compose types`
# - size is in MiB
rhel_image_builder_image_formats:
  - type: qcow2
    size: 10240

# override osbuilder built-in system repos
# each item in the list must consist of a filename that matches
# one found in /usr/share/osbuild-composer/repositories (the
# built-in repos), and content in YAML format that translates
# into the relevant JSON used in the file.  for example:
# rhel_image_builder_system_repos:
#   - filename: rhel-86.json
#     content:
#       x86_64:
#         - name: baseos
#           baseurl: http://proxy.lab.home/repos/rhel-8-for-x86_64-baseos-rpms/
#           gpgkey: '{{ lookup("file", "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release") }}'
#           rhsm: false
#           check_gpg: true
#         - name: appstream
#           baseurl: http://proxy.lab.home/repos/rhel-8-for-x86_64-appstream-rpms/
#           gpgkey: '{{ lookup("file", "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release") }}'
#           rhsm: false
#           check_gpg: true
rhel_image_builder_system_repos: []


...
# vim: ft=yaml.ansible
