---
- name: Ensure image builder and dependencies are installed
  ansible.builtin.yum:
    name: '{{ rhel_image_builder_packages }}'
    state: present
  register: _package_install

- name: Enable osbuild-composer socket
  # noqa: no-handler
  ansible.builtin.systemd:
    name: osbuild-composer.socket
    state: started
    enabled: true
  when: _package_install is changed

- name: Ensure cockpit-composer and dependencies are installed
  ansible.builtin.yum:
    name: '{{ rhel_image_builder_cockpit_packages }}'
    state: present
  when: rhel_image_builder_install_cockpit | bool
  register: _cockpit_install

- name: Enable cockpit socket
  # noqa: no-handler
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true
  when: _cockpit_install is changed

# TODO: add tasks to create repo JSON files in /etc/osbuild-composer/repositories
- name: Create system repo overrides directory
  ansible.builtin.file:
    path: /etc/osbuild-composer/repositories
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create system repo overrides
  ansible.builtin.copy:
    content: '{{ item.content | to_nice_json }}'
    dest: /etc/osbuild-composer/repositories/{{ item.filename }}
    owner: root
    group: root
    mode: 0644
  loop: '{{ rhel_image_builder_system_repos }}'
  when: rhel_image_builder_system_repos
  notify: Restart osbuild-composer.service


...
# vim: ft=yaml.ansible
