---
- name: Run image builder installation tasks
  include_tasks:
    file: install.yml
    apply:
      tags: install
  when: rhel_image_builder_install | bool
  tags: install

- name: Run image build tasks
  include_tasks:
    file: image.yml
    apply:
      tags: image
  tags: image

...
# vim: ft=yaml.ansible
